name = "GAIO"
uuid = "33d280d1-ac47-4b0f-9c2e-fa6a385d0226"
authors = ["The GAIO.jl Team"]
version = "0.6.1"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HostCPUFeatures = "3e5b6fbb-0976-4d2c-9146-d79de83f2fb0"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixNetworks = "4f449596-a032-5618-b826-5a251cb6dc11"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SplitOrderedCollections = "4b700b29-7da4-4670-af42-5a9783ffd6e0"
SplittablesBase = "171d559e-b47b-412a-8079-5efa626c420e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DynamicalSystemsBase = "6e36e845-645a-534a-86f2-f5d4aa5a06b4"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
CUDAExt = "CUDA"
DynamicalSystemsExt = "DynamicalSystemsBase"
MakieExt = "Makie"
MetaGraphsNextExt = "MetaGraphsNext"
MetalExt = "Metal"
PlotsExt = "Plots"

[compat]
Arpack = "0.5"
CUDA = "5"
DynamicalSystemsBase = "3"
FLoops = "0.2"
GeometryBasics = "0.2, 0.3, 0.4"
Graphs = "1.9"
HostCPUFeatures = "0.1"
IntervalArithmetic = "0.18, 0.19, 0.20, 0.21, 0.22"
LinearAlgebra = "1.9"
Makie = "0.17, 0.18, 0.19, 0.20"
MatrixNetworks = "1"
MetaGraphsNext = "0.4, 0.5, 0.6, 0.7"
Metal = "1"
MuladdMacro = "0.2"
OrderedCollections = "1.4"
Plots = "1"
PrecompileTools = "1"
ProgressMeter = "1"
SparseArrays = "1"
SplitOrderedCollections = "0.1"
SplittablesBase = "0.1"
StaticArrays = "1"
TupleTools = "1"
julia = "1.10"
