name = "GAIO"
uuid = "33d280d1-ac47-4b0f-9c2e-fa6a385d0226"
authors = ["The GAIO.jl Team"]
version = "0.1.0"

[deps]
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
